# ============================================================
#  SWFE837 – FreeRADIUS clients.conf (TP2)
#  Déclare les NAS (Network Access Servers) autorisés
#  → ici, l'AP hostapd en local
# ============================================================

client localhost {
    ipaddr          = 127.0.0.1
    secret          = labo_secret_2026
    shortname       = ap-labo
    require_message_authenticator = no
}

# Si votre AP est sur une autre machine du réseau labo :
# client 192.168.1.10 {
#     ipaddr  = 192.168.1.10
#     secret  = labo_secret_2026
#     shortname = ap-distant
# }
