# ============================================================
#  SWFE837 – Configuration dnsmasq pour Evil Twin (TP3)
#  Fournit DHCP et DNS aux clients connectés au Rogue AP
# ============================================================

interface=wlan2
dhcp-range=192.168.99.10,192.168.99.50,255.255.255.0,12h
dhcp-option=3,192.168.99.1    # Passerelle par défaut
dhcp-option=6,192.168.99.1    # Serveur DNS

# Résoudre tous les noms vers l'attaquant (portail captif optionnel)
# address=/#/192.168.99.1

log-dhcp
log-queries
