

interface=wlan0
driver=nl80211
ssid=SWFE837-WPA3-Enterprise
hw_mode=g
channel=6
ieee80211n=1

wpa=2
wpa_key_mgmt=WPA-EAP-SHA256
wpa_pairwise=CCMP
rsn_pairwise=CCMP

ieee8021x=1
auth_server_addr=127.0.0.1
auth_server_port=1812
auth_server_shared_secret=labo_secret_2026
eap_server=0

