# ============================================================
#  SWFE837 – wpa_supplicant.conf WPA2-PSK (TP1)
#  Simule le client Nexellia connecté à l'AP
# ============================================================
ctrl_interface=/run/wpa_supplicant
update_config=1

network={
    ssid="NexelliaWifi"
    psk="labo2026"
    key_mgmt=WPA-PSK
}
